---
kind: Template
apiVersion: v1
labels:
  app: webhook-proxy
  template: webhook-proxy-template
metadata:
  name: webhook-proxy
  annotations:
    openshift.io/display-name: webhook proxy
    tags: webhook,proxy,webhook-proxy

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: ${WEBHOOK_PROXY_NAME}
      name: ${WEBHOOK_PROXY_NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      labels:
        app: ${WEBHOOK_PROXY_NAME}
      name: ${WEBHOOK_PROXY_NAME}
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: ${WEBHOOK_PROXY_IMAGE_STREAM_TAG}
      resources: {}
      source:
        type: Git
        git:
          uri: ${REPO_URL}
          ref: ${REPO_REF}
      strategy:
        type: Docker
        dockerStrategy:
          noCache: true
          forcePull: true
      triggers:
        - type: ConfigChange
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 2
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${WEBHOOK_PROXY_NAME}
    spec:
      replicas: 1
      selector:
        name: ${WEBHOOK_PROXY_NAME}
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            name: ${WEBHOOK_PROXY_NAME}
        spec:
          containers:
            - name: ${WEBHOOK_PROXY_NAME}
              image: ${WEBHOOK_PROXY_IMAGE_STREAM_TAG}
              imagePullPolicy: IfNotPresent
              resources:
                limits:
                  memory: "1Gi"
                  cpu: "1000m"
                requests:
                  memory: "500Mi"
                  cpu: "512m"
              securityContext:
                capabilities: {}
                privileged: false
              terminationMessagePath: /dev/termination-log
              env:
                - name: JENKINS_URL
                  valueFrom:
                    secretKeyRef:
                      name: github-jenkins-trigger-url
                      key: jenkins_url
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: webhook-aws-access-key-id
                      key: id
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: webhook-aws-secret-access-key
                      key: secret
                - name: SQS_QUEUE
                  valueFrom:
                    secretKeyRef:
                      name: webhook-sqs-queue-name
                      key: queue_name
                - name: SQS_REGION
                  valueFrom:
                    secretKeyRef:
                      name: webhook-sqs-queue-region
                      key: queue_region
          dnsPolicy: ClusterFirst
          restartPolicy: Always
      triggers:
        - type: "ConfigChange"
        - type: "ImageChange"
          imageChangeParams:
            automatic: true
            containerNames:
              - ${WEBHOOK_PROXY_NAME}
            from:
              kind: "ImageStreamTag"
              name: ${WEBHOOK_PROXY_IMAGE_STREAM_TAG}
# global parameters
parameters:
  - description: Git repository with Dockerfile and master entrypoint.
    displayName: Repository URL
    name: REPO_URL
    value: https://github.com/virt-s1/webhook-proxy.git
    required: true
  - description: The git ref or tag to use for customization.
    displayName: Git Reference
    name: REPO_REF
    value: main
  - name: WEBHOOK_PROXY_NAME
    displayName: webhook proxy APP name
    description: The name of the webhook proxy application.
    value: webhook-proxy
  - name: WEBHOOK_PROXY_IMAGE_STREAM_TAG
    displayName: webhook proxy ImageStreamTag
    description: Name of the ImageStreamTag to be used for the webhook proxy image.
    value: webhook-proxy:latest
